# Default headers for all requests
headers:
  - "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
  - "Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8"
  - "Accept-Language: en-US,en;q=0.9"
  - "Accept-Encoding: gzip, deflate"
  - "Connection: keep-alive"

# Crawling options
options:
  # Request options
  timeout: 10
  retries: 1
  delay: 100
  rate-limit: 150
  concurrency: 10

  # Crawling behavior
  max-depth: 3
  form-fields: false
  known-files: true
  robots-txt: true
  sitemap-xml: true
  js-crawl: true

  # System settings
  disable-ipv6: true
  system-resolvers: true

  # Output settings
  json: true
  output-fields:
    - url
    - path
    - method
    - status
    - title
    - tag
